#!/bin/bash -e

docker build -t url_checker .
git clone https://github.com/EbookFoundation/free-programming-books.git /tmp/workdir/fpb
docker run -v /tmp/workdir/fpb:/tmp/fpb -it url_checker /tmp/fpb/free-programming-books.md
